
service: helloWorld

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: ap-southeast-2	# Sydney

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /hello
          method: get

